### ISSUE TITLE
Новости удаляются после рестарта докера

### ISSUE THREAD

**Issue by maxfarseer** [maxfarseer/backend-tz3#1]
Если запускать приложение через докер, то после перезапуска докера новости удаляются.

**Comment by mkitez** [comment]
Дожно быть поправлено [в этом коммите](https://github.com/maxfarseer/backend-tz3/commit/f651c82f5d98a6feae6c7ded1534490c9e6d92a5).

**Comment by maxfarseer** [comment]
Проверено, работает.
