### ISSUE TITLE
401 при авторизации с reCaptcha

### ISSUE THREAD

**Issue by sinneren** [maxfarseer/backend-tz3#4]
Посылаю POST-запрос с токеном рекапчи на **/users**, в ответ приходит _Error: Request failed with status code 401_.
Как я понял, нужно сделать авторизацию с Secret-key от рекапчи в сваггере.

**Comment by mkitez** [comment]
На бэкенд вам нужно отправлять ответ от рекапчи вместе с логином и паролем, а не секретный ключ. Смотрите документацию https://developers.google.com/recaptcha/docs/display. При этом вам нужно указать свой ключ в конфиге бэкенда в файле _backend/config/env/common.js_.

**Comment by sinneren** [comment]
Разумеется отправляю всё сразу. Вот про конфиг я и забыл совсем, спасибо.

**Comment by sinneren** [comment]
Указал. Сделал docker-compose down, снова up. И всё равно 401.  `{"error":"Captcha is not passed"}`
Я использую вот этот пакет https://github.com/dozoisch/react-google-recaptcha он под 2 рекапчу, может бек под 3ю или это не важно?

**Comment by mkitez** [comment]
Этот пакет должен работать. С докером попробуйте `docker-compose up --build`.
