### ISSUE TITLE
ошибка docker-compose up

### ISSUE THREAD

**Issue by pbdgk** [maxfarseer/backend-tz3#5]
не могу нормально запустить докер.... свагер и монго запускаются, но не сервер.
Может банальная ошибка, но пока никак с ней не справлюсь..

вот лог.. 

```
backend_1  | npm WARN deprecated yarn@0.24.6: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
backend_1  | npm WARN tz3-backend@1.0.0 No repository field.
backend_1  | 
backend_1  | npm ERR! code E404
backend_1  | npm ERR! 404 Not Found: flatmap-stream@https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.2.tgz
backend_1  | 
backend_1  | npm ERR! A complete log of this run can be found in:
backend_1  | npm ERR!     /root/.npm/_logs/2018-11-28T20_55_46_736Z-debug.log
backend_1  | start.sh: line 10: ./node_modules/yarn/bin/yarn: No such file or directory
backend_1  | start.sh: line 11: ./node_modules/yarn/bin/yarn: No such file or directory
backendtz3_backend_1 exited with code 127
```

**Comment by pbdgk** [comment]
разобрался.
проблема была в зависимисти nodemon от библиотеки pstree 

https://github.com/remy/nodemon/issues/1468

проблему решил путем удаления ./backend/package-lock.json
плюс в package.json поменял версию nodemon на @1.18.7, которая уже зависит от корректной  pstree @1.1.2

Может кому-то поможет данное решение. Делал как умел, если есть более элегантное решение, буду рад увидеть.

**Comment by sinneren** [comment]
Уточнение. Надо удалить yarn.lock, package-lock.json. Потом docker-compose down, docker-compose up --build. Может что-то лишнее, но только так смог побороть
