### ISSUE TITLE
Нам нужен user._id !!!

### ISSUE THREAD

**Issue by pbdgk** [maxfarseer/backend-tz3#7]
## Суть пробемы:
На всех endpoint'ах связанных c аутентификацией - в респонсе сервера мы получаем только JWT, без user_id

## Почему это проблема:
Нам необходимо качественно определить является ли пользователь автором новости или нет (Что важно для возможности редактирования или удаления и вообще отображения кнопок или иконок).

## Почему не стоит привязываться в полю displayName.
Это поле находится в feed.creator (лежит рядом с id)
Получаем с 
```
get <api url>/news/feeds 
get <api url>/news/feeds/:id)
```
Его легко получить с каждой новоcти, также легко получить если пользователь зашел через Google Oauth2 -> googleUser.getBasicProfile().getName()
#### НО!
1. оно не является уникальным, что критически важно для определения автора.
2. если заходим без гугл auth (recapcha sign up / sign in ) мы его получить не можем.
разве что догадаться, что dispalyName будет полем username и запомнить его когда пользователь заходит или регистрируется (что как по мне плохой вариант решения).

## Как можно получить user._id на данном этапе.
Единственный способ получить айди пользователя, что вошел, это получить список новостей, и последовательно ломиться на endpoint 
```
get <api url>/news/user/:id  (этот айди берем из feed.creator._id)
```
если сервер ответит с кодом респонса 200 - значит это наш айди, так как получить данные по этому endpoint может только пользователь с JWT, который относится к этому аккаунту.

То есть решение является ужасным костылем, так как в худшем случае количество запросов на сервер будет равно количеству новостей, только для того, чтобы "ПОПЫТАТЬСЯ" найти id нашего пользователя.

Причем если не нашли значит у пользователь не постил ни одной записи.

## Пути решения:
1) возращать на всех endpoint`ах где возращается jwt еще и id пользователя.
2) добавить endpoint 
```
get <api url>/user-id
header: { 
    'x-acces-token': jwt
} 
```
на котором проверятеся jwt и если такой пользователь существует - то вернуть его id в респонсе.

#### Возможно я ошибаюсь и просто не вижу правильного решения.
Если я прав, могу попробовать дописать backend используя один из предложенных мной путей решения, или же другой путь, предложенный кем-то еще, если он будет значительно лучше.

**Comment by De-Santa** [comment]
Нормально ты расписал )
в JWT токен зашифрован id пользователя, тебе надо на клиенте декодировать токен (гугли parse jwt token) и там ты найдешь id пользователя

**Comment by pbdgk** [comment]
@De-Santa шикарно! спасибо! Вы полностью правы, как я мог забыть об этом.
